services:
  app:
    image: app
    build: .
    environment:
      NODE_ENV: development
    container_name: nes-service-node-server
    command: npm run dev
    ports:
      - 4321:4321
    volumes:
      - .:/app
      - /app/node_modules