services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: henwr123
      POSTGRES_PASSWORD: wellme123
    expose:
      - 5432
    volumes:
      - nes-db:/var/lib/postgresql/data
      - ./data/initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: nes-service-api
    build: .
    environment:
      NODE_ENV: development
      APP_DB_HOST: db
      APP_DB_USER: henwr123
      APP_DB_PASSWORD: wellme123
    container_name: nes-service-api
    command: npm run dev
    ports:
      - 4321:4321
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
#  api-test:
#    image: nes-service-api
#    command: npm run test
#    environment:
#      APP_URL: http://localhost:4321
#      APP_DB_HOST: db
#      APP_DB_USER: henwr123
#      APP_DB_PASSWORD: wellme123
#    depends_on:
#      - db
#      - api
volumes:
  nes-db:
    driver: local
